# Here is a link to the documentation for this template 
# https://cert-manager.io/docs/configuration/acme/

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  namespace: lionel
spec:
  acme:
    # The ACME production api URL
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email address used for ACME registration
    email: lionel.daubichon@alterway.fr

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt

    # Enable the HTTP-01 challenge provider
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
