apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: lionel
  name: mysqlpv2
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
