apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
  namespace: lionel
    app: wordpress
  name: wordpress-mysql
spec:
  selector:
    matchLabels:
      app: wordpress-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
