apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  namespace: lionel
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lionel.daubichon@alterway.fr 
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx

